modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "ionapi"
version = "0.1.0"
displayName = "Ion Multiplatform API"
authors = "Chris"
description = '''A tiny personal multiplatform API for Fabric and NeoForge mods.'''

[[dependencies.ionapi]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.76,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ionapi]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2]"
ordering = "NONE"
side = "BOTH"
